### ISSUE TITLE
error running RAILS_ENV=development bin/delayed_job start

### ISSUE THREAD

**Issue by aristosv** [vteams/open-source-billing#108]
I got to the part where I have to run this command

`RAILS_ENV=development bin/delayed_job start`

and I got this error

```
accounting@accounting:~/open-source-billing$ RAILS_ENV=development bin/delayed_job start
DEPRECATION WARNING: Single arity template handlers are deprecated. Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
  >> #<#<Class:0x0000561cf5eb5948>:0x0000561cf6131820>.call(template)
To:
  >> #<#<Class:0x0000561cf5eb5948>:0x0000561cf6131820>.call(template, source)
 (called from <top (required)> at /home/accounting/open-source-billing/config/application.rb:8)
[DEPRECATION] This gem has been renamed to hashie-forbidden_attributes and will no longer be supported. Please switch to hashie-forbidden_attributes as soon as possible.
Traceback (most recent call last):
	39: from bin/delayed_job:3:in `<main>'
	38: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	37: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	36: from /home/accounting/open-source-billing/config/environment.rb:5:in `<top (required)>'
	35: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/application.rb:363:in `initialize!'
	34: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	33: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	32: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	31: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	30: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `call'
	29: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each'
	28: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	27: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	26: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:415:in `call'
	25: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	24: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/initializable.rb:50:in `each'
	23: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	22: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	21: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	20: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	19: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	18: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	17: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `run'
	16: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	15: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/engine.rb:623:in `block in <class:Engine>'
	14: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/engine.rb:623:in `each'
	13: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
	12: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/engine.rb:666:in `load_config_initializer'
	11: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:182:in `instrument'
	10: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/engine.rb:667:in `block in load_config_initializer'
	 9: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `load'
	 8: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	 7: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `block in load'
	 6: from /home/accounting/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `load'
	 5: from /home/accounting/open-source-billing/config/initializers/config.rb:1:in `<top (required)>'
	 4: from /home/accounting/open-source-billing/config/initializers/config.rb:2:in `<module:OSB>'
	 3: from /home/accounting/open-source-billing/config/initializers/config.rb:4:in `<module:CONFIG>'
	 2: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/psych.rb:577:in `load_file'
	 1: from /home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/psych.rb:577:in `open'
/home/accounting/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - /home/accounting/open-source-billing/config/config.yml (Errno::ENOENT)
```

Any idea what could it mean?

**Comment by aristosv** [comment]
I guess this software is no longer supported.

**Comment by sapioXmachina** [comment]
@aristosv i know this is closed but wanted to provide some feedback -- hopefully someone @OSB will see this since it was recently updated on 2/24/2023!

the second deprecation error re: `hashie_rails` can be fixed by swapping to the newer gem `hashie-forbidden_attributes' mentioned in the error log

[see here](https://github.com/Maxim-Filimonov/hashie_rails)

however that first deprecation error is still an issue for me:
```
Bundle updated!
~/open-source-billing $ rails s
DEPRECATION WARNING: Single arity template handlers are deprecated. Template handlers must now accept two parameters, the view object and the source for the view object.
Change:
>> #<#<Class:0x00007f986cc1128>:0x00007f986cbf1420>.call(template)
TO:
>> #<#<Class:0x00007f986cc1128>:0x00007f986cf1420>.call(template, source) (called from <top (required)> at ~/open-source-billing/config/
application.rb:8)
dyld [71349]: missing symbol called
zsh: abort rails
```
