### ISSUE TITLE
cannot load such file -- regin/parser

### ISSUE THREAD

**Issue by bitbox** [vteams/open-source-billing#24]
Hello,

I'm really new to Ruby (on Rails) but very interested in deploying OSB.
I've setup a RoR droplet at Digital Ocean, it is using Unicorn (+nginx)

It is pretty hard to figure out how to deploy OSB as I couldn't find any documentation except for the README.md on GitHub. But after some experimentation I achieved to have Unicorn launching without throwing errors, here is what is in **/home/unicorn/log/unicorn.log**:
```
I, [2015-05-26T02:00:57.925876 #16744]  INFO -- : listening on addr=127.0.0.1:8080 fd=10
I, [2015-05-26T02:00:57.926295 #16744]  INFO -- : worker=0 spawning...
I, [2015-05-26T02:00:57.927005 #16744]  INFO -- : master process ready
I, [2015-05-26T02:00:57.936003 #16747]  INFO -- : worker=0 spawned pid=16747
I, [2015-05-26T02:00:57.946400 #16747]  INFO -- : Refreshing Gem list
I, [2015-05-26T02:01:01.479268 #16747]  INFO -- : worker=0 ready
```

Unfortunately, whenever I try to access the web interface, the following error is logged in the **log/production.log** file:
```
Started GET "/" for xxx.xxx.xxx.xxx at 2015-05-26 02:01:13 +0000

LoadError (cannot load such file -- regin/parser):
  rack-mount (0.8.3) lib/rack/mount/utils.rb:157:in `rescue in parse_regexp'
  rack-mount (0.8.3) lib/rack/mount/utils.rb:129:in `parse_regexp'
  rack-mount (0.8.3) lib/rack/mount/generatable_regexp.rb:65:in `block in segments'
  rack-mount (0.8.3) lib/rack/mount/generatable_regexp.rb:64:in `catch'
  rack-mount (0.8.3) lib/rack/mount/generatable_regexp.rb:64:in `segments'
  rack-mount (0.8.3) lib/rack/mount/generatable_regexp.rb:32:in `extended'
  rack-mount (0.8.3) lib/rack/mount/route.rb:47:in `extend'
  rack-mount (0.8.3) lib/rack/mount/route.rb:47:in `block in initialize'
  rack-mount (0.8.3) lib/rack/mount/route.rb:39:in `each'
  rack-mount (0.8.3) lib/rack/mount/route.rb:39:in `initialize'
  rack-mount (0.8.3) lib/rack/mount/route_set.rb:68:in `new'
  rack-mount (0.8.3) lib/rack/mount/route_set.rb:68:in `add_route'
  grape (0.9.0) lib/grape/endpoint.rb:96:in `block (2 levels) in mount_in'
  grape (0.9.0) lib/grape/endpoint.rb:95:in `each'
  grape (0.9.0) lib/grape/endpoint.rb:95:in `block in mount_in'
  grape (0.9.0) lib/grape/endpoint.rb:90:in `each'
  grape (0.9.0) lib/grape/endpoint.rb:90:in `mount_in'
  grape (0.9.0) lib/grape/endpoint.rb:88:in `block in mount_in'
  grape (0.9.0) lib/grape/endpoint.rb:88:in `each'
  grape (0.9.0) lib/grape/endpoint.rb:88:in `mount_in'
  grape (0.9.0) lib/grape/api.rb:122:in `block in initialize'
  grape (0.9.0) lib/grape/api.rb:121:in `each'
  grape (0.9.0) lib/grape/api.rb:121:in `initialize'
  grape (0.9.0) lib/grape/api.rb:30:in `new'
  grape (0.9.0) lib/grape/api.rb:30:in `compile'
  grape (0.9.0) lib/grape/api.rb:38:in `block in call'
  grape (0.9.0) lib/grape/api.rb:38:in `synchronize'
  grape (0.9.0) lib/grape/api.rb:38:in `call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  rack-cors (0.3.1) lib/rack/cors.rb:72:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/application.rb:144:in `call'
  railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
  unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
  unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
  unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
  unicorn (4.8.3) bin/unicorn:126:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.1.3/bin/unicorn:23:in `load'
  /usr/local/rvm/gems/ruby-2.1.3/bin/unicorn:23:in `<main>'
  /usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
  /usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
```

I'm using RVM, and have tried many things to figure out what prevents the rack-mount code to correctly load the parser.rb file that effectively exists under **/usr/local/rvm/gems/ruby-2.1.3/gems/rack-mount-0.8.3/lib/rack/mount/vendor/regin**, but never succeeded.

My **gem env** is:
```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.1.3 (2014-09-19 patchlevel 242) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-2.1.3
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-2.1.3/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-2.1.3/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-2.1.3
     - /usr/local/rvm/gems/ruby-2.1.3@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/rvm/gems/ruby-2.1.3/bin
     - /usr/local/rvm/gems/ruby-2.1.3@global/bin
     - /usr/local/rvm/rubies/ruby-2.1.3/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /usr/local/rvm/bin
     - /usr/local/rvm/bin
```

Any help would be greatly appreciated, thanks in advance

**Comment by shahzad-nxb** [comment]
We are unable to reproduce this issue on our local systems and Amazon servers. We did never get this issue on local or production environment. Further we also used unicorn as server and it worked fine. 

For OSB development, we are using ruby 2.0.0 and recommend using ruby 2.0.0 for its installation. 

Please share details/steps to reproduce this issue so that we may be able to solve this issue after reproducing it on our side.

**Comment by bitbox** [comment]
First off, thank you for paying attention to my question.

I've given another try at the OSB installation but still reaching the same result:
```
LoadError (cannot load such file -- regin/parser):
  rack-mount (0.8.3) lib/rack/mount/utils.rb:157:in `rescue in parse_regexp'
```
I'll try to describe as exactly as possible what was done, who knows if we reach success this might be useful as a base for a tutorial ;-)

Using a Digital Ocean's droplet (virtual server) based on their "application" image:
**Ruby on Rails on Ubuntu 14.04 x64 vmlinuz-3.13.0-27-generic (Nginx + Unicorn)**
**Installed packages:**
- rvm 1.25.31 (stable)
- gem 2.2.2

Find here [an introduction on this droplet](https://www.digitalocean.com/community/tutorials/how-to-use-the-1-click-ruby-on-rails-on-ubuntu-14-04-image)

As you stated you are using ruby 2.0.0, I first installed it using rvm (stopping the unicorn service beforehand):

#### Install ruby 2.0.0 environment
Logged in as root:
```
> service unicorn stop
 * Stopping Unicorn web server unicorn                                      [ OK ]

> rvm list
rvm rubies
   ruby-2.0.0-p353 [ x86_64 ]
=* ruby-2.1.3 [ x86_64 ]
# => - current
# =* - current && default
#  * - default

> rvm install 2.0.0
Searching for binary rubies, this might take some time.
Found remote file https://rvm.io/binaries/ubuntu/14.04/x86_64/ruby-2.0.0-p576.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
...
ruby-2.0.0-p576 - #gemset created /usr/local/rvm/gems/ruby-2.0.0-p576@global
ruby-2.0.0-p576 - #importing gemset /usr/local/rvm/gemsets/global.gems
...
ruby-2.0.0-p576 - #gemset created /usr/local/rvm/gems/ruby-2.0.0-p576
ruby-2.0.0-p576 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
...

> rvm use ruby-2.0.0-p576 --default
```
At this stage we have:
```
> gem list
*** LOCAL GEMS ***
bigdecimal (1.2.0)
bundler (1.7.3)
bundler-unload (1.0.2)
executable-hooks (1.3.2)
gem-wrappers (1.2.5)
io-console (0.4.2)
json (1.7.7)
minitest (4.3.2)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
test-unit (2.0.0.0)
```
And the content of **/usr/local/rvm/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/environment**:
```
> cat /usr/local/rvm/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/environment
export PATH="/usr/local/rvm/gems/ruby-2.0.0-p576@global/bin:/usr/local/rvm/rubies/ruby-2.0.0-p576/bin:$PATH"
export GEM_HOME='/usr/local/rvm/gems/ruby-2.0.0-p576@global'
export GEM_PATH='/usr/local/rvm/gems/ruby-2.0.0-p576@global'
export MY_RUBY_HOME='/usr/local/rvm/rubies/ruby-2.0.0-p576'
export IRBRC='/usr/local/rvm/rubies/ruby-2.0.0-p576/.irbrc'
unset MAGLEV_HOME
unset RBXOPT
export RUBY_VERSION='ruby-2.0.0-p576'
```

#### Install unicorn

Modify **/etc/default/unicorn** to fit the new environment:
```
> gem install unicorn
Fetching: rack-1.6.1.gem (100%)
Successfully installed rack-1.6.1
Fetching: kgio-2.9.3.gem (100%)
Building native extensions.  This could take a while...
...
4 gems installed

> nano /etc/default/unicorn
PATH=/usr/local/rvm/gems/ruby-2.0.0-p576@global/bin:/usr/local/rvm/rubies/ruby-2.0.0-p576/bin:/home/unicorn/.rvm/bin:/usr/local/sbin:/usr/bin:/bin:/sbin:$
export GEM_HOME=/usr/local/rvm/gems/ruby-2.0.0-p576:/usr/local/rvm/gems/ruby-2.0.0-p576@global
export GEM_PATH=/usr/local/rvm/gems/ruby-2.0.0-p576:/usr/local/rvm/gems/ruby-2.0.0-p576@global 
DAEMON=/usr/local/rvm/gems/ruby-2.0.0-p576/bin/unicorn
```

#### Install OSB Bundle

On the RoR Droplet, Unicorn serves Ruby on Rails applications and looks for files in **/home/rails**.
All files from the github repo were transferred to /home/rails.

Note that 3 system packages had to be installed to prevent errors during the charlock_holmes and rmagick gems installation.

```
> apt-get install libicu-dev ImageMagick libmagickwand-dev
...
...
> cd /home/rails
> bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your
bundle as root will break this application for all non-root users on this machine.
Fetching source index from https://rubygems.org/
Installing rake 10.4.2
Installing abstract_type 0.0.7
...
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from money:
Please note the following API changes in Money version 6
 - Money#amount, Money#dollars methods now return instances of BigDecimal (rather than Float).
Please read the migration notes at https://github.com/RubyMoney/money#migration-notes
and choose the migration that best suits your application.
Test responsibly :-)
Post-install message from bcrypt-ruby:
#######################################################
The bcrypt-ruby gem has changed its name to just bcrypt.  Instead of
installing `bcrypt-ruby`, you should install `bcrypt`.  Please update your
dependencies accordingly.
#######################################################
Post-install message from rmagick:
Please report any bugs. See https://github.com/gemhome/rmagick/compare/RMagick_2-13-2...master and https://github.com/rmagick/rmagick/issues/18
Post-install message from twitter-bootstrap-rails:
Important: You may need to add a javascript runtime to your Gemfile in order for bootstrap's LESS files to compile to CSS. 
**********************************************
ExecJS supports these runtimes:
therubyracer - Google V8 embedded within Ruby
therubyrhino - Mozilla Rhino embedded within JRuby
Node.js
Apple JavaScriptCore - Included with Mac OS X
Microsoft Windows Script Host (JScript)
**********************************************
```

Use `RAILS_ENV=production bundle exec rspec` to detect potential problems (note that this outputs a very long list that I will not reproduce here)

#### Modify OSB configuration files to fit our environment:

**config/database.yml**:
```
> cp -a /home/rails/config/database.yml.backup /home/rails/config/database.yml
> nano /home/rails/config/database.yml
...
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails
  pool: 5
  username: rails
  password: **********
  host: localhost
```

**config/initializers/config.rb**:
```
> find / -name "wkhtmltopdf"
/usr/local/rvm/gems/ruby-2.0.0-p576/bin/wkhtmltopdf
/usr/local/rvm/gems/ruby-2.0.0-p576/gems/wkhtmltopdf-binary-0.9.9.3/bin/wkhtmltopdf

> nano config/initializers/config.rb
...
APP_HOST ||= '000.000.000.000' # e.g. osb.mydomain.com
...
WKHTMTTOPDF_PATH ||= '/usr/local/rvm/gems/ruby-2.0.0-p576/bin/wkhtmltopdf'
...
<email settings>
```
The above lines were adapted to our specific situation.

#### Database setup and assets compilation:
Then have the OSB database set up, and compile the assets:
```
> cd /home/rails
> RAILS_ENV=production rake db:create
> RAILS_ENV=production rake db:migrate
> RAILS_ENV=production rake db:seed
> RAILS_ENV=production bundle exec rake assets:precompile
```

#### Sorting out errors
Now try to start the unicorn service while, in order to "debug" the process, we observe the unicorn logs: **/home/unicorn/log/unicorn.log**.
```
FIRST SESSION
> tail -f /home/unicorn/log/unicorn.log

PARALLEL SESSION
> service unicorn start
when error shows:
> service unicorn stop
```
We stop the service to avoid very long log to scan.
Whenever the log does **NOT** stop on a line like:
```
[2015-05-26T16:08:23.775808 #12620]  INFO -- : worker=0 ready
```
It means something went wrong. Analyzing the log messages can indicate what the problem is for example:
```
E, [2015-05-26T16:06:41.342936 #12578] ERROR -- : Permission denied - log/production.log (Errno::EACCES)
```
Indicates the app cannot access the production.log file. This happens when it already exists but has rights set incorrectly. Deleting the production.log file will solve this error.

Another error type that may be encountered is:
```
You have already activated rack 1.6.1, but your Gemfile requires rack 1.5.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```
In this case we had 2 versions of rack, uninstalling the latest one solved the problem:
```
> gem list rack
*** LOCAL GEMS ***
descendants_tracker (0.0.4)
rack (1.6.1, 1.5.2)
rack-accept (0.4.5)
rack-cors (0.3.1)
rack-mount (0.8.3)
rack-test (0.6.2)

> gem uninstall rack
Select gem to uninstall:
 1. rack-1.6.1
 2. rack-1.5.2
 3. All versions
> 1
Successfully uninstalled rack-1.6.1
```
After this, unicorn started without error.

### Try to access OSB
Now that Unicorn is working, we try to access the OSB app through a web browser pointing at the server IP. During this, we observe OSB's production.log file: **/home/rails/log/production.log**.
```
> tail -f /home/rails/log/production.log

Started HEAD "/" for xxx.xxx.xxx.xxx at 2015-05-26 17:16:42 +0000

LoadError (cannot load such file -- regin/parser):
  rack-mount (0.8.3) lib/rack/mount/utils.rb:157:in `rescue in parse_regexp'
  rack-mount (0.8.3) lib/rack/mount/utils.rb:129:in `parse_regexp'
  ...
```

And **this is where I'm stuck !**

Thank you for helping me out of this, or at least point me in a right direction as I'm getting out of inspiration on how to solve this.

**Comment by shahzad-nxb** [comment]
Thanks for sharing details. Steps you mentioned above are similar for any rails application installation and it should work fine. We have investigated and found that issue is due to 'rack-mount' gem which is dependency of 'grape' gem used for restful apis.
https://github.com/rack/rack/issues/552

'rack-mount' is probably not actively developed/maintained now a days and its github page (https://github.com/josh/rack-mount) is also closed. 

We are trying to reproduce issue and then solve this issue. We may better solve this issue If you can give us access to your digital ocean droplet. You can also contact us via email (matrix-dev@nxvt.com or imran@nxvt.com)

**Comment by bitbox** [comment]
The best way to give you access to the droplet would for you to send me your id_rsa.pub key so I can give you root access to the VM.

I'm sending an e-mail to both addresses you mention in order to carry this out in a more discrete manner than on this GitHub page ;-)

Thank you for paying attention to this problem.

**Comment by bitbox** [comment]
Thank you for fixing this guys, you are great !

Since I'm new to RoR I'm currently not able to give detailed information on **HOW** to fix this but I'll already copy what you wrote in the e-mail in case it might be of use for someone else reading this:

> I have fixed issue and it is now working fine.
>
> It was due to bug in 'rack-mount' gem which is dependency of 'grape' gem we used for development of restful API's. To sort it out, i have mounted grape api to '/api' instead of application root. We have also noted this issue and will fix it in next release.

FYI: as of this writing current commit = 1dc3e9dadfee4d2a7ff1d567e4cb3e03a3e764ae

I'm not marking this issue as closed yet, as someone might find the time to detail the operations needed to achieve what is described.

Thank you.
