### ISSUE TITLE
Quote support

### ISSUE THREAD

**Issue by fredscud** [vteams/open-source-billing#73]
Hi,
Do you plan to add quotes ?
Thanks,
Fred.

**Comment by D4V3M0NK** [comment]
Estimates are the same thing, are they not?

**Comment by freman** [comment]
Estimates don't seem to be working very well.

I can generate an invoice just fine, but if I put the same parameters into an estimate I get the following

```
Started POST "/en/estimates" for 124.170.90.124 at 2018-12-12 12:09:31 +0000
Processing by EstimatesController#create as JS
  Parameters: {"utf8"=>"✓", "estimate"=>{"estimate_date"=>"2018-12-12", "client_id"=>"1", "estimate_line_items_attributes"=>{"0"=>{"_destroy"=>"false", "item_id"=>"4", "item_name"=>"Sealing", "item_description"=>"Apply sealer", "item_unit_cost"=>"10.00", "item_quantity"=>"1", "tax_1"=>"1", "tax_2"=>""}, "1"=>{"_destroy"=>"false", "item_id"=>"5", "item_name"=>"Silicone", "item_description"=>"Silicone as required per lm", "item_unit_cost"=>"5.50", "item_quantity"=>"1", "tax_1"=>"1", "tax_2"=>""}, "2"=>{"_destroy"=>"false", "item_id"=>"2", "item_name"=>"Hourly Rate", "item_description"=>"Carry out remedial works per hr", "item_unit_cost"=>"60.00", "item_quantity"=>"1", "tax_1"=>"1", "tax_2"=>""}}, "discount_type"=>"%", "tax_id"=>"", "sub_total"=>"83.05", "discount_amount"=>"0.00", "discount_percentage"=>"", "estimate_tax_amount"=>"0", "tax_amount"=>"8.30", "estimate_total"=>"83.05", "notes"=>""}, "save_as_draft"=>"save_as_draft", "locale"=>"en"}
  User Load (0.1ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
Unpermitted parameter: tax_id
  Role Load (0.1ms)  SELECT `roles`.* FROM `roles` INNER JOIN `users_roles` ON `roles`.`id` = `users_roles`.`role_id` WHERE `users_roles`.`user_id` = 1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))
Unpermitted parameter: tax_id
   (0.2ms)  BEGIN
  Currency Load (0.2ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`unit` = 'AUD'  ORDER BY `currencies`.`id` ASC LIMIT 1
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 47ms (ActiveRecord: 0.8ms)

NoMethodError (undefined method `invoice_line_items' for #<Estimate:0x00007fa1b50d2e98>
Did you mean?  invoice_date):
  app/models/estimate.rb:258:in `update_estimate_total'
  app/models/estimate.rb:205:in `create_line_item_taxes'
  app/controllers/estimates_controller.rb:58:in `create'
```

It's also not currency safe?
![image](https://user-images.githubusercontent.com/506680/49868903-7d72fe00-fe5a-11e8-949f-448a738837e5.png)

**Comment by imranmalik** [comment]
Issues with estimate section have been fixed in latest release
