### ISSUE TITLE
can't send email

### ISSUE THREAD

**Issue by cryptooth** [vteams/open-source-billing#86]
Hi there,
My installation on Ubuntu 14.04
using standart smtp settings with my own server
But when I click to email send button on any invoice, I'm getting error on console:

```
2019-05-24T22:45:37.620Z 15796 TID-htfrg WARN: PaymentMailer.payment_notification_email job argument is 15108 bytes, you should refactor it to reduce the size
Completed 500 Internal Server Error in 73ms (ActiveRecord: 6.2ms)

Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):
  app/models/payment.rb:203:in `notify_client'
  app/controllers/payments_controller.rb:72:in `block in create'
  app/controllers/payments_controller.rb:69:in `create'


  Rendered /home/kayhan/.rvm/gems/ruby-2.3.7/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.2ms)
  Rendered /home/kayhan/.rvm/gems/ruby-2.3.7/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.5ms)
  Rendered /home/kayhan/.rvm/gems/ruby-2.3.7/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.5ms)
  Rendered /home/kayhan/.rvm/gems/ruby-2.3.7/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (14.2ms)

```

any advice?

**Comment by cryptooth** [comment]
This error resolved after installing Redis. But still can't send email.

**Comment by imranmalik** [comment]
You need to start sidekiq to process emails in the background using following command:

  bundle exec sidekiq -e production

To read more about sidekiq, follow below link
https://github.com/mperham/sidekiq
